### ISSUE TITLE
The details about  algorithms 

### ISSUE THREAD

**Issue by Xinchungeorb** [layer6ai-labs/ProxyFL#1]
Thanks for your code!
Sorry to bother you. I want to know how the algorithms compare like FedAvg ,FML ,ProxyFL. I can't seem to find the details about them in your code. 
Thx！I am looking forward to your reply ！

**Comment by shivamkalra** [comment]
Hi Xinchungeorb. Thanks for posting your question. The code for each algorithm is in: https://github.com/layer6ai-labs/ProxyFL/blob/main/trainer.py. `train_proxy_push` is ProxyFL, `train_fml` is FML, `train_avg` is FedAvg and so on.
