### ISSUE TITLE
Where can I get fashion-mnist in npz format?

### ISSUE THREAD

**Issue by zhanz5** [layer6ai-labs/ProxyFL#2]
Where can I get fashion-mnist in npz format?

**Comment by zhujian129** [comment]
换数据集运行需要修改哪个地方？

**Comment by JesseCresswell** [comment]
Tensorflow has a function for loading fmnist data
https://www.tensorflow.org/api_docs/python/tf/keras/datasets/fashion_mnist/load_data
Once it's loaded, you can use numpy to save it as a npz if you need to.
